/** Centralized Turkish UI copy for Milestone 1. Easy to extract later for i18n. */

export const ui = {
  brand: "PodTest Network",
  tagline: "Yazılım, kalite, kariyer ve PodTest’in arkasındaki insanlar.",
  nav: {
    home: "Ana sayfa",
    members: "Üyeler",
    community: "Topluluk",
    episodes: "Bölümler",
    profile: "Profilim",
    messages: "Mesajlar",
    arayanlar: "Arayanlar",
    host: "Sunucu",
    admin: "Yönetim",
    signIn: "Giriş",
    signUp: "Kayıt ol",
    signOut: "Çıkış",
  },
  landing: {
    title: "PodTest Network",
    lead: "Yazılım, kalite, mühendislik ve kariyer etrafında açık bir topluluk. Herkes katılabilir; üyelik için başvuru, mülakat veya test görevi yok.",
    ctaJoin: "Katıl",
    ctaBrowse: "Üyelere göz at",
    ctaArayanlar: "PodTest Arayanlar'a katıl",
    laterNote: "Ödemeler ve Catchylabs bağlantısı yol haritasında — henüz burada değil.",
  },
  auth: {
    registerTitle: "Hesap oluştur",
    loginTitle: "Giriş yap",
    email: "E-posta",
    password: "Şifre",
    name: "Görünen ad",
    submitRegister: "Kayıt ol",
    submitLogin: "Giriş yap",
    haveAccount: "Zaten hesabın var mı?",
    needAccount: "Hesabın yok mu?",
  },
  onboarding: {
    title: "Hoş geldin",
    lead: "Profilini şimdi doldurabilir veya sonra tamamlayabilirsin. Hiçbir alan zorunlu değil.",
    skip: "Şimdilik geç",
    continueProfile: "Profilime git",
  },
  profile: {
    title: "Profilim",
    visibilityTitle: "Görünürlük",
    visibilityBody:
      "Profilin varsayılan olarak özel taslaktır. Yayımlamak için incelemeye gönderirsin; onaylanana kadar kamuya açık sayfada ve üye dizininde görünmez. Bekleyen düzenlemeler onaylı genel görünüme sızmaz.",
    draftHint: "Bu alanlar taslağındır. Onaysız değişiklikler kamuya yansımaz.",
    submitReview: "Yayımlamak için incelemeye gönder",
    unpublish: "Yayımdan kaldır",
    preview: "Önizleme",
    save: "Kaydet",
    status: "Durum",
    manualReviewNote: "Yayın incelemesi şu an manueldir (Milestone 1).",
    statuses: {
      DRAFT: "Taslak",
      PENDING_REVIEW: "İnceleme bekliyor",
      APPROVED: "Onaylandı / yayında",
      REJECTED: "Reddedildi",
      UNPUBLISHED: "Yayımdan kaldırıldı",
    },
  },
  directory: {
    title: "Üyeler",
    empty: "Henüz keşfedilebilir, onaylı bir üye profili yok.",
    filters: "Filtreler",
    skill: "Beceri",
    openToWork: "İş arıyor",
    hiring: "İşe alıyor",
    openToProjects: "Projeye açık",
    apply: "Uygula",
  },
  admin: {
    title: "Yönetim",
    reviews: "Profil yayın incelemeleri",
    empty: "Bekleyen inceleme yok.",
    approve: "Onayla",
    reject: "Reddet",
    reason: "Red nedeni",
    manualBanner: "Manuel moderasyon — otomatik içerik denetimi henüz yok.",
  },
  community: {
    title: "Topluluk soruları",
    lead: "İsteyen her üye soru sorabilir ve cevap yazabilir. CV, ilgi alanları veya genel profil zorunlu değildir. Katılım isteğe bağlıdır.",
    ask: "Soru sor",
    askTitle: "Soru sor",
    askLead:
      "Önce taslak olarak saklayabilirsin. Yayımlamadan önce içeriğin ve görünen adının kamuya açık olacağını onaylaman gerekir.",
    empty: "Henüz yayımlanmış soru yok.",
    episodes: "Podcast bölümleri",
    episodesTitle: "Podcast bölümleri",
    episodesLead:
      "Yalnızca yönetici tarafından yayımlanmış bölümler listelenir. Dinleme bağlantıları haricidir; Spotify hesabı veya otomatik içe aktarma yoktur.",
  },
  common: {
    loading: "Yükleniyor…",
    error: "Bir şeyler ters gitti.",
    comingLater: "Yakında",
  },
} as const;
