/** Centralized Turkish UI copy. Easy to extract later for i18n. */

export const ui = {
  brand: "PodTest Network",
  tagline: "Yazılım, kalite ve kariyer etrafında açık bir topluluk.",
  nav: {
    home: "Ana sayfa",
    members: "Üyeler",
    community: "Topluluk",
    episodes: "Bölümler",
    jobs: "İş ilanları",
    employer: "İşveren",
    employerArea: "İşveren alanı",
    profile: "Profilim",
    account: "Hesabım",
    messages: "Mesajlar",
    notifications: "Bildirimler",
    arayanlar: "Kariyer Portresi",
    host: "Sunucu",
    hostArea: "Sunucu alanı",
    admin: "Yönetim",
    signIn: "Giriş",
    signUp: "Kayıt ol",
    signOut: "Çıkış",
  },
  landing: {
    brand: "PodTest Network",
    title: "Yazılım, kalite ve kariyer etrafında açık bir topluluk.",
    lead: "İnsanlarla tanış, deneyimini paylaş, yeni bölümler keşfet ve profesyonel olarak görünür ol.",
    reassuranceLead: "Üyelik için başvuru, mülakat veya test görevi yok.",
    reassuranceFollow: "Profilini oluştur, topluluğa katıl.",
    /** Combined form retained for older call sites */
    reassurance:
      "Üyelik için başvuru, mülakat veya test görevi yok. Profilini oluştur, topluluğa katıl.",
    ctaJoin: "Topluluğa katıl",
    ctaEpisodes: "Bölümleri keşfet",
    ctaArayanlar: "Kariyer Portresi'ni keşfet",
    /** @deprecated kept for older call sites; prefer ctaEpisodes */
    ctaBrowse: "Bölümleri keşfet",
    openTitle: "Herkes katılabilir",
    openBody:
      "Konuşmacı, içerik üreticisi veya belirli bir şirkette çalışıyor olman gerekmez. Yazılım ve kalite dünyasının herhangi bir yerindeysen; öğrenmek, paylaşmak veya deneyimini görünür kılmak için yerin var.",
    whatTitle: "Ne var?",
    /** Compact hero orientation — keep shorter than lower-page what.* */
    heroWhat: {
      community: {
        title: "Topluluk",
        body: "İnsanlarla tanış ve görünür ol.",
      },
      episodes: {
        title: "PodTest bölümleri",
        body: "Konuşmaları ve yeni bölümleri keşfet.",
      },
      kariyer: {
        title: "Kariyer Portresi",
        body: "CV'nin arkasındaki insanı ve düşünme biçimini görünür kıl.",
      },
    },
    what: {
      community: {
        title: "Topluluk",
        body: "Yazılım ve kalite dünyasından insanlarla tanış, profilini oluştur ve bağlantı kur.",
        href: "/uyeler",
        linkLabel: "Üyelere göz at",
      },
      episodes: {
        title: "PodTest bölümleri",
        body: "Yeni ve geçmiş bölümleri keşfet, konuşmaları takip et.",
        href: "/bolumler",
        linkLabel: "Bölümleri keşfet",
      },
      kariyer: {
        title: "Kariyer Portresi",
        body: "CV'nin ötesine geç. Deneyimini, nasıl düşündüğünü ve bundan sonra ne aradığını anlatan kısa bir profesyonel kayıt oluştur.",
        href: "/arayanlar",
        linkLabel: "Kariyer Portresi'ni keşfet",
      },
    },
    latestEpisodes: "Son bölümler",
    allEpisodes: "Tüm bölümler",
    noEpisodes: "Henüz yayımlanmış bölüm yok.",
  },
  auth: {
    registerTitle: "Hesap oluştur",
    loginTitle: "Giriş yap",
    email: "E-posta",
    password: "Şifre",
    name: "Görünen ad",
    submitRegister: "Kayıt ol",
    submitLogin: "Giriş yap",
    haveAccount: "Zaten hesabın var mı?",
    needAccount: "Hesabın yok mu?",
  },
  onboarding: {
    title: "Hoş geldin",
    lead: "Profilini şimdi doldurabilir veya sonra tamamlayabilirsin. Hiçbir alan zorunlu değil.",
    skip: "Şimdilik geç",
    continueProfile: "Profilime git",
  },
  profile: {
    title: "Profilim",
    tabInfo: "Profil bilgileri",
    tabCv: "CV ile destek",
    tabVisibility: "Görünürlük",
    visibilityTitle: "Görünürlük",
    visibilityBody:
      "Profilin varsayılan olarak özeldir. Yayımlamak için incelemeye gönderirsin; onaylanana kadar herkese açık sayfada ve üye dizininde görünmez.",
    draftHint: "Düzenlediğin alanlar özel taslaktır. Onaylanmadan kamuya yansımaz.",
    submitReview: "İncelemeye gönder",
    submitDisabledPending: "İnceleme bekleniyor — yeni gönderim için sonucu bekle.",
    unpublish: "Yayımdan kaldır",
    previewDraft: "Taslak önizleme",
    previewPublic: "Herkese açık görünüm",
    save: "Kaydet",
    status: "Durum",
    reviewNote: "Yayın incelemesi manueldir; otomatik onay yoktur.",
    pendingWhilePublished:
      "Herkese açık bir sürümün yayında. Bekleyen düzenlemelerin onaylanana kadar kamuya yansımaz.",
    privateDraftHelp: "Profilin şu an özel. Hazır olduğunda incelemeye gönderebilirsin.",
    statuses: {
      DRAFT: "Özel taslak",
      PENDING_REVIEW: "İnceleme bekliyor",
      APPROVED: "Yayında",
      REJECTED: "Reddedildi",
      UNPUBLISHED: "Yayımdan kaldırıldı",
    },
  },
  directory: {
    title: "Üyeler",
    lead: "Birlikte çalışabileceğin ve fikir alışverişi yapabileceğin insanlarla tanış.",
    empty: "Henüz keşfedilebilir, onaylı bir üye profili yok. Filtreleri temizleyip yeniden deneyebilirsin.",
    emptyFiltered: "Bu filtrelere uyan üye yok. Filtreleri sıfırlayıp yeniden dene.",
    filters: "Filtreler",
    skill: "Beceri",
    openToWork: "İş arıyor",
    hiring: "İşe alıyor",
    openToProjects: "Projeye açık",
    apply: "Uygula",
    reset: "Sıfırla",
  },
  admin: {
    title: "Yönetim",
    reviews: "Profil yayın incelemeleri",
    empty: "Bekleyen inceleme yok.",
    approve: "Onayla",
    reject: "Reddet",
    reason: "Red nedeni",
    manualBanner: "Yayın ve rapor incelemeleri manueldir. Yardımcı taramalar yalnızca ipucu verir; otomatik onay yoktur.",
  },
  community: {
    title: "Topluluk",
    lead: "Sorunu paylaş, deneyimini aktar, sohbete katıl.",
    ask: "Soru sor",
    askTitle: "Soru sor",
    askLead:
      "Önce taslak olarak saklayabilirsin. Yayımlamadan önce içeriğin ve görünen adının kamuya açık olacağını onaylaman gerekir.",
    empty: "Henüz yayımlanmış soru yok. İlk soruyu sen sorabilirsin.",
    moderationNearAsk:
      "Yayımlanan içerik kural tabanlı bir kontrolden geçer; belirsiz içerik bekletilir. Bu otomatik bir yapay zekâ onay ürünü değildir.",
    episodes: "Podcast bölümleri",
    episodesTitle: "Bölümler",
    episodesLead: "PodTest sohbetlerini keşfet ve dinle.",
  },
  arayanlar: {
    title: "Kariyer Portresi",
    lead:
      "CV ne yaptığını söylüyor. Biz biraz da nasıl düşündüğünü göstermek istiyoruz. 15–20 dakikalık kısa bir profesyonel kayıt; bu bir iş görüşmesi değil.",
    apply: "Kariyer Portresi'ne başvur",
    continue: "Başvuruma devam et",
    viewPrep: "Notlarımı aç",
    viewStatus: "Hazırlık durumunu gör",
    restart: "Yeniden başla",
    fromCv: "CV'mden bölüm hazırlığına başla",
    fromCvNote:
      "Mevcut özel CV'nden düzenlenebilir öneriler üretilir. Onaylamadan paylaşılmaz; ekstra AI kredisi alınmaz.",
  },
  hiring: {
    title: "İşveren",
    lead: "Gönüllü yayımlanmış profiller üzerinde arama yapın, ilan verin ve aday listelerini yönetin. İletişim mevcut mesaj isteği sistemiyle ve adayın onayıyla ilerler.",
    jobsPublic: "İş ilanları",
    jobsPublicLead: "Yalnızca yayımlanmış ve süresi dolmamış ilanlar listelenir.",
    applyExternal: "Harici başvuru bağlantısı",
    applyMessage: "Mesaj isteği ile iletişim",
    pilotLimitJobs: "Pilot sınırı: çalışma alanı başına bir aktif yayımlanmış ilan.",
    createJob: "İlan oluştur",
    createJobLead: "Taslak oluşturup inceleme veya yayım için gönderin. İlanlar sessizce otomatik onaylanmaz.",
    noWorkspace: "İlan vermek için önce bir çalışma alanı oluşturmanız gerekir.",
    noPilotAccess:
      "İşveren pilot yetkisi yok. İlan oluşturma etkinleştirilmedi; yetki atlanarak düğme açılmaz.",
    slotsExhausted:
      "Aktif yayımlı ilan kotası dolu. Yeni ilan göndermek için mevcut yayımlı ilanı kapatın. PodTest+ yükseltmesi yakında — ödeme yok.",
    methodExternal: "Harici HTTPS başvuru adresi",
    methodMessaging: "Çalışma alanı üyesine mesaj isteği",
    contactMember: "İletişim için görevli üye",
  },
  common: {
    loading: "Yükleniyor…",
    error: "Bir şeyler ters gitti.",
    comingLater: "Yakında",
    footer: "PodTest Network · açık üyelik topluluğu",
  },
} as const;
