services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: podtest
      POSTGRES_PASSWORD: podtest
      POSTGRES_DB: podtest
    volumes:
      - podtest_pg:/var/lib/postgresql/data
      - ./docker/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro

volumes:
  podtest_pg:
